#!/usr/bin/perl
use strict;
use warnings;

# A script to calculate the % polymorphic sites specifically from files generated
# by ambig.pl.
# Script counts all the Hetz positions and divides by the total number of sites (-n) * 100 (%)

use Getopt::Std;
my %opts;
# accept input file -i (argument)
getopts('i:o:', \%opts);
unless ($opts{i})
{
    print "\ncalculate the % polymorphic sites specifically from files generated by ambig.pla and append to file";
    print "\nEnter -i input file\nEnter -o output file\n\n";
    exit;
}

# Open file
unless (open(IN, $opts{i}))
{
    print "\nI Can't open file\nClosing script\n";
    exit;
}
open (OUTFILE, ">$opts{o}");
print OUTFILE "";
close OUTFILE;
open (OUTFILE, ">>$opts{o}");
print OUTFILE "Sequence,M,R,W,S,Y,K,V H D or B,n,Total,%Hetz\n";
foreach my $line (<IN>)
{
    if ($line =~ m/^>/)
    {
        chomp $line;
        my @array = split(/,/, $line);
        $array[10] = ($array[1]+$array[2]+$array[3]+$array[4]+$array[5]+$array[6])/($array[9]-$array[8])*100;
        $array[11] = "\n";
        #print OUTFILE "@array\n";
        print OUTFILE join (",", @array);
    }
}